### ISSUE TITLE
CSV output files needs to have consistent headers

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timestreamlib#170]
(from Riyan)
_GC02L files have two header lines whereas others have one header line. This inconsistency can lead to unnecessary errors or crash the program, given that it is not much likely I'll check all the data sheets every time._

I think the current version is that the first row should be the plantID and the second the pot number. Please verify that this is what the code is doing and fix any files in bvz0036 that don't have the correct header.

**Comment by Joelgranados** [comment]
This is not a bug. This is something that we discussed some time ago and decided that we should include two headers because some use cases might require two headers to be in place. Here is the issue https://github.com/borevitzlab/timestreamlib/issues/165.

If the CSV files have two headers, then just remove the one you don't need. There is no need to rerun the whole pipeline to remove one line.
